// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseStationModel.proto

package com.glsx.pb;

public final class BaseStationModel {
  private BaseStationModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseStationReqMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string sn = 2;
    /**
     * <code>required string sn = 2;</code>
     */
    boolean hasSn();
    /**
     * <code>required string sn = 2;</code>
     */
    java.lang.String getSn();
    /**
     * <code>required string sn = 2;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    // required string gpsTime = 3;
    /**
     * <code>required string gpsTime = 3;</code>
     */
    boolean hasGpsTime();
    /**
     * <code>required string gpsTime = 3;</code>
     */
    java.lang.String getGpsTime();
    /**
     * <code>required string gpsTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getGpsTimeBytes();

    // optional string mcc = 4;
    /**
     * <code>optional string mcc = 4;</code>
     */
    boolean hasMcc();
    /**
     * <code>optional string mcc = 4;</code>
     */
    java.lang.String getMcc();
    /**
     * <code>optional string mcc = 4;</code>
     */
    com.google.protobuf.ByteString
        getMccBytes();

    // optional string mnc = 5;
    /**
     * <code>optional string mnc = 5;</code>
     */
    boolean hasMnc();
    /**
     * <code>optional string mnc = 5;</code>
     */
    java.lang.String getMnc();
    /**
     * <code>optional string mnc = 5;</code>
     */
    com.google.protobuf.ByteString
        getMncBytes();

    // optional string lac = 6;
    /**
     * <code>optional string lac = 6;</code>
     */
    boolean hasLac();
    /**
     * <code>optional string lac = 6;</code>
     */
    java.lang.String getLac();
    /**
     * <code>optional string lac = 6;</code>
     */
    com.google.protobuf.ByteString
        getLacBytes();

    // optional string cellId = 7;
    /**
     * <code>optional string cellId = 7;</code>
     */
    boolean hasCellId();
    /**
     * <code>optional string cellId = 7;</code>
     */
    java.lang.String getCellId();
    /**
     * <code>optional string cellId = 7;</code>
     */
    com.google.protobuf.ByteString
        getCellIdBytes();

    // optional string accessTime = 8;
    /**
     * <code>optional string accessTime = 8;</code>
     */
    boolean hasAccessTime();
    /**
     * <code>optional string accessTime = 8;</code>
     */
    java.lang.String getAccessTime();
    /**
     * <code>optional string accessTime = 8;</code>
     */
    com.google.protobuf.ByteString
        getAccessTimeBytes();
  }
  /**
   * Protobuf type {@code protobuf.BaseStationReqMessage}
   */
  public static final class BaseStationReqMessage extends
      com.google.protobuf.GeneratedMessage
      implements BaseStationReqMessageOrBuilder {
    // Use BaseStationReqMessage.newBuilder() to construct.
    private BaseStationReqMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseStationReqMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseStationReqMessage defaultInstance;
    public static BaseStationReqMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseStationReqMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseStationReqMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sn_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              gpsTime_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mcc_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              mnc_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              lac_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              cellId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              accessTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.glsx.pb.BaseStationModel.internal_static_protobuf_BaseStationReqMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.glsx.pb.BaseStationModel.internal_static_protobuf_BaseStationReqMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.glsx.pb.BaseStationModel.BaseStationReqMessage.class, com.glsx.pb.BaseStationModel.BaseStationReqMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseStationReqMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseStationReqMessage>() {
      public BaseStationReqMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseStationReqMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseStationReqMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string sn = 2;
    public static final int SN_FIELD_NUMBER = 2;
    private java.lang.Object sn_;
    /**
     * <code>required string sn = 2;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sn = 2;</code>
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sn = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string gpsTime = 3;
    public static final int GPSTIME_FIELD_NUMBER = 3;
    private java.lang.Object gpsTime_;
    /**
     * <code>required string gpsTime = 3;</code>
     */
    public boolean hasGpsTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string gpsTime = 3;</code>
     */
    public java.lang.String getGpsTime() {
      java.lang.Object ref = gpsTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gpsTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string gpsTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGpsTimeBytes() {
      java.lang.Object ref = gpsTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gpsTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string mcc = 4;
    public static final int MCC_FIELD_NUMBER = 4;
    private java.lang.Object mcc_;
    /**
     * <code>optional string mcc = 4;</code>
     */
    public boolean hasMcc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string mcc = 4;</code>
     */
    public java.lang.String getMcc() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mcc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mcc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMccBytes() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mcc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string mnc = 5;
    public static final int MNC_FIELD_NUMBER = 5;
    private java.lang.Object mnc_;
    /**
     * <code>optional string mnc = 5;</code>
     */
    public boolean hasMnc() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string mnc = 5;</code>
     */
    public java.lang.String getMnc() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mnc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mnc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMncBytes() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string lac = 6;
    public static final int LAC_FIELD_NUMBER = 6;
    private java.lang.Object lac_;
    /**
     * <code>optional string lac = 6;</code>
     */
    public boolean hasLac() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string lac = 6;</code>
     */
    public java.lang.String getLac() {
      java.lang.Object ref = lac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lac_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lac = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLacBytes() {
      java.lang.Object ref = lac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string cellId = 7;
    public static final int CELLID_FIELD_NUMBER = 7;
    private java.lang.Object cellId_;
    /**
     * <code>optional string cellId = 7;</code>
     */
    public boolean hasCellId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string cellId = 7;</code>
     */
    public java.lang.String getCellId() {
      java.lang.Object ref = cellId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cellId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cellId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCellIdBytes() {
      java.lang.Object ref = cellId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cellId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string accessTime = 8;
    public static final int ACCESSTIME_FIELD_NUMBER = 8;
    private java.lang.Object accessTime_;
    /**
     * <code>optional string accessTime = 8;</code>
     */
    public boolean hasAccessTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string accessTime = 8;</code>
     */
    public java.lang.String getAccessTime() {
      java.lang.Object ref = accessTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accessTime = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTimeBytes() {
      java.lang.Object ref = accessTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
      sn_ = "";
      gpsTime_ = "";
      mcc_ = "";
      mnc_ = "";
      lac_ = "";
      cellId_ = "";
      accessTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGpsTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getGpsTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMccBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMncBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLacBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCellIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getAccessTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getGpsTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMccBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMncBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLacBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCellIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getAccessTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.glsx.pb.BaseStationModel.BaseStationReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.glsx.pb.BaseStationModel.BaseStationReqMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.BaseStationReqMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.glsx.pb.BaseStationModel.BaseStationReqMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.glsx.pb.BaseStationModel.internal_static_protobuf_BaseStationReqMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.glsx.pb.BaseStationModel.internal_static_protobuf_BaseStationReqMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.glsx.pb.BaseStationModel.BaseStationReqMessage.class, com.glsx.pb.BaseStationModel.BaseStationReqMessage.Builder.class);
      }

      // Construct using com.glsx.pb.BaseStationModel.BaseStationReqMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gpsTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mcc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        mnc_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        lac_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cellId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        accessTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.glsx.pb.BaseStationModel.internal_static_protobuf_BaseStationReqMessage_descriptor;
      }

      public com.glsx.pb.BaseStationModel.BaseStationReqMessage getDefaultInstanceForType() {
        return com.glsx.pb.BaseStationModel.BaseStationReqMessage.getDefaultInstance();
      }

      public com.glsx.pb.BaseStationModel.BaseStationReqMessage build() {
        com.glsx.pb.BaseStationModel.BaseStationReqMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.glsx.pb.BaseStationModel.BaseStationReqMessage buildPartial() {
        com.glsx.pb.BaseStationModel.BaseStationReqMessage result = new com.glsx.pb.BaseStationModel.BaseStationReqMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gpsTime_ = gpsTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mcc_ = mcc_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mnc_ = mnc_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lac_ = lac_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cellId_ = cellId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.accessTime_ = accessTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.glsx.pb.BaseStationModel.BaseStationReqMessage) {
          return mergeFrom((com.glsx.pb.BaseStationModel.BaseStationReqMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.glsx.pb.BaseStationModel.BaseStationReqMessage other) {
        if (other == com.glsx.pb.BaseStationModel.BaseStationReqMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasSn()) {
          bitField0_ |= 0x00000002;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasGpsTime()) {
          bitField0_ |= 0x00000004;
          gpsTime_ = other.gpsTime_;
          onChanged();
        }
        if (other.hasMcc()) {
          bitField0_ |= 0x00000008;
          mcc_ = other.mcc_;
          onChanged();
        }
        if (other.hasMnc()) {
          bitField0_ |= 0x00000010;
          mnc_ = other.mnc_;
          onChanged();
        }
        if (other.hasLac()) {
          bitField0_ |= 0x00000020;
          lac_ = other.lac_;
          onChanged();
        }
        if (other.hasCellId()) {
          bitField0_ |= 0x00000040;
          cellId_ = other.cellId_;
          onChanged();
        }
        if (other.hasAccessTime()) {
          bitField0_ |= 0x00000080;
          accessTime_ = other.accessTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSn()) {
          
          return false;
        }
        if (!hasGpsTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.glsx.pb.BaseStationModel.BaseStationReqMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.glsx.pb.BaseStationModel.BaseStationReqMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // required string sn = 2;
      private java.lang.Object sn_ = "";
      /**
       * <code>required string sn = 2;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sn = 2;</code>
       */
      public java.lang.String getSn() {
        java.lang.Object ref = sn_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sn = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        java.lang.Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sn = 2;</code>
       */
      public Builder setSn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 2;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 2;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }

      // required string gpsTime = 3;
      private java.lang.Object gpsTime_ = "";
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public boolean hasGpsTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public java.lang.String getGpsTime() {
        java.lang.Object ref = gpsTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          gpsTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGpsTimeBytes() {
        java.lang.Object ref = gpsTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gpsTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public Builder setGpsTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gpsTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public Builder clearGpsTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gpsTime_ = getDefaultInstance().getGpsTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string gpsTime = 3;</code>
       */
      public Builder setGpsTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gpsTime_ = value;
        onChanged();
        return this;
      }

      // optional string mcc = 4;
      private java.lang.Object mcc_ = "";
      /**
       * <code>optional string mcc = 4;</code>
       */
      public boolean hasMcc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string mcc = 4;</code>
       */
      public java.lang.String getMcc() {
        java.lang.Object ref = mcc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mcc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mcc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMccBytes() {
        java.lang.Object ref = mcc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mcc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mcc = 4;</code>
       */
      public Builder setMcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mcc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mcc = 4;</code>
       */
      public Builder clearMcc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mcc_ = getDefaultInstance().getMcc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mcc = 4;</code>
       */
      public Builder setMccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mcc_ = value;
        onChanged();
        return this;
      }

      // optional string mnc = 5;
      private java.lang.Object mnc_ = "";
      /**
       * <code>optional string mnc = 5;</code>
       */
      public boolean hasMnc() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string mnc = 5;</code>
       */
      public java.lang.String getMnc() {
        java.lang.Object ref = mnc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mnc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mnc = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMncBytes() {
        java.lang.Object ref = mnc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mnc = 5;</code>
       */
      public Builder setMnc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mnc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnc = 5;</code>
       */
      public Builder clearMnc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mnc_ = getDefaultInstance().getMnc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnc = 5;</code>
       */
      public Builder setMncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mnc_ = value;
        onChanged();
        return this;
      }

      // optional string lac = 6;
      private java.lang.Object lac_ = "";
      /**
       * <code>optional string lac = 6;</code>
       */
      public boolean hasLac() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string lac = 6;</code>
       */
      public java.lang.String getLac() {
        java.lang.Object ref = lac_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lac = 6;</code>
       */
      public com.google.protobuf.ByteString
          getLacBytes() {
        java.lang.Object ref = lac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lac = 6;</code>
       */
      public Builder setLac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lac = 6;</code>
       */
      public Builder clearLac() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lac_ = getDefaultInstance().getLac();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lac = 6;</code>
       */
      public Builder setLacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        lac_ = value;
        onChanged();
        return this;
      }

      // optional string cellId = 7;
      private java.lang.Object cellId_ = "";
      /**
       * <code>optional string cellId = 7;</code>
       */
      public boolean hasCellId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string cellId = 7;</code>
       */
      public java.lang.String getCellId() {
        java.lang.Object ref = cellId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cellId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cellId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCellIdBytes() {
        java.lang.Object ref = cellId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cellId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cellId = 7;</code>
       */
      public Builder setCellId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        cellId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellId = 7;</code>
       */
      public Builder clearCellId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cellId_ = getDefaultInstance().getCellId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellId = 7;</code>
       */
      public Builder setCellIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        cellId_ = value;
        onChanged();
        return this;
      }

      // optional string accessTime = 8;
      private java.lang.Object accessTime_ = "";
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public boolean hasAccessTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public java.lang.String getAccessTime() {
        java.lang.Object ref = accessTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accessTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTimeBytes() {
        java.lang.Object ref = accessTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public Builder setAccessTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        accessTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public Builder clearAccessTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        accessTime_ = getDefaultInstance().getAccessTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessTime = 8;</code>
       */
      public Builder setAccessTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        accessTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.BaseStationReqMessage)
    }

    static {
      defaultInstance = new BaseStationReqMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.BaseStationReqMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BaseStationReqMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BaseStationReqMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BaseStationModel.proto\022\010protobuf\"\215\001\n\025B" +
      "aseStationReqMessage\022\014\n\004type\030\001 \002(\t\022\n\n\002sn" +
      "\030\002 \002(\t\022\017\n\007gpsTime\030\003 \002(\t\022\013\n\003mcc\030\004 \001(\t\022\013\n\003" +
      "mnc\030\005 \001(\t\022\013\n\003lac\030\006 \001(\t\022\016\n\006cellId\030\007 \001(\t\022\022" +
      "\n\naccessTime\030\010 \001(\tB\037\n\013com.glsx.pbB\020BaseS" +
      "tationModel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_BaseStationReqMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_BaseStationReqMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_BaseStationReqMessage_descriptor,
              new java.lang.String[] { "Type", "Sn", "GpsTime", "Mcc", "Mnc", "Lac", "CellId", "AccessTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
